<?php

namespace Tests\Unit\User;

use App\Services\User\CreateUserService;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class CreateUserTest extends TestCase
{
    use RefreshDatabase;

    protected CreateUserService $createUser;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->createUser = app()->make(CreateUserService::class);
    }

    /**
     * A basic unit test example.
     */
    public function test_user_created(): void
    {
        $user = $this->createUser->execute('John', 'email@email.com', 'password');
        $this->assertEquals('John', $user->name);
    }
}
