<?php

namespace Tests\Unit\Geo;

use App\Services\Geo\CalcDistanceBetweenPoints;
use PHPUnit\Framework\TestCase;

class CalcDistanceBetweenPointsTest extends TestCase
{
    protected CalcDistanceBetweenPoints $calcDistanceBetweenPoints;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->calcDistanceBetweenPoints = app()->make(CalcDistanceBetweenPoints::class);
    }

    /**
     * A basic unit test example.
     */
    public function test_distance_calculated(): void
    {
        $distance = $this->calcDistanceBetweenPoints->execute(-6.36188, 143.23070, -6.14774, 143.65716);
        $this->assertIsInt($distance);
        $this->assertEquals(28, $distance);
    }
}
