<?php

namespace Tests\Unit\Contracts;

use App\Services\Contracts\GenerateContractHeader;
use PHPUnit\Framework\TestCase;

class GenerateContractHeaderTest extends TestCase
{
    protected GenerateContractHeader $generateContractHeader;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->generateContractHeader = app()->make(GenerateContractHeader::class);
    }

    /**
     * A basic unit test example.
     */
    public function test_header_is_generated_for_one_leg(): void
    {
        $legs = [
            [
                'cargo_desc' => 'desc',
                'cargo_type' => 1,
                'cargo_qty' => 1000,
                'dep_airport_id' => 'AYMR',
                'current_airport_id' => 'AYMR',
                'arr_airport_id' => 'AYMN',
                'distance' => 10,
                'heading' => 65
            ]
        ];
        $header = $this->generateContractHeader->execute('AYMR', $legs);
        $this->assertEquals('AYMR', $header['origin_airport_id']);
        $this->assertEquals(1, $header['legs']);
    }

    public function test_header_is_generated_for_two_legs(): void
    {
        $legs = [
            [
                'cargo_desc' => 'desc',
                'cargo_type' => 1,
                'cargo_qty' => 1000,
                'dep_airport_id' => 'AYMR',
                'current_airport_id' => 'AYMR',
                'arr_airport_id' => 'AYMN',
                'distance' => 10,
                'heading' => 65
            ],
            [
                'cargo_desc' => 'desc',
                'cargo_type' => 1,
                'cargo_qty' => 1000,
                'dep_airport_id' => 'AYMR',
                'current_airport_id' => 'AYMR',
                'arr_airport_id' => 'AYMN',
                'distance' => 10,
                'heading' => 65
            ]
        ];
        $header = $this->generateContractHeader->execute('AYMR', $legs);
        $this->assertEquals('AYMR', $header['origin_airport_id']);
        $this->assertEquals(2, $header['legs']);
    }
}
