<?php

namespace Tests\Unit\Contracts;

use App\Models\Airport;
use App\Services\Contracts\GenerateContracts;
use Database\Seeders\AirportSeeder;
use Database\Seeders\CargoTypeSeeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class GenerateContractsTest extends TestCase
{
    use RefreshDatabase;

    protected GenerateContracts $generateContracts;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->generateContracts = app()->make(GenerateContracts::class);
        $seeder = new AirportSeeder();
        $seeder->run();
        $cseeder = new CargoTypeSeeder();
        $cseeder->run();
    }

    /**
     * A basic unit test example.
     */
    public function test_contract_array_returned(): void
    {
        $airport = Airport::where('identifier', 'AYMR')->first();
        $airports = Airport::where('identifier', '<>', 'AYMR')->get();
        $contracts = $this->generateContracts->execute($airport, 2, $airports);
        $this->assertIsArray($contracts);
    }
}
