<?php

namespace Tests\Unit\Finance;

use App\Enums\AirlineTransactionTypes;
use App\Services\Finance\AddAirlineTransaction;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AddAirlineTransactionTest extends TestCase
{
    use RefreshDatabase;

    protected AddAirlineTransaction $addAirlineTransaction;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->addAirlineTransaction = app()->make(AddAirlineTransaction::class);
    }

    /**
     * A basic unit test example.
     */
    public function test_positive_transaction(): void
    {
        $this->addAirlineTransaction->execute(AirlineTransactionTypes::PILOT_BONUS, 100.00);
        $this->assertDatabaseHas('airline_transactions', [
            'transaction_type' => AirlineTransactionTypes::PILOT_BONUS,
            'total' => 100.00
        ]);
    }

    public function test_negative_transaction(): void
    {
        $this->addAirlineTransaction->execute(AirlineTransactionTypes::PILOT_BONUS, -100.00);
        $this->assertDatabaseHas('airline_transactions', [
            'transaction_type' => AirlineTransactionTypes::PILOT_BONUS,
            'total' => -100.00
        ]);
    }
}
